######################################################################
# Automatically generated by qmake (3.0) Tue Jun 25 11:57:43 2013
######################################################################

TEMPLATE = app
TARGET = qmllint
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += qml-private core-private
